devex: adding rfc template
quarylabs/quary pull request #199
Opened 2024-05-14 16:05 UTC by benfdking

2024-05-14 16:07 UTC, louisjoecodes requested changes
I would change it to Feature Request. RFC is confusing

2024-05-14 16:40 UTC, benfdking commented
We already have a Feature Request, I do think it might be nice to have a more RFC like document where you can write a proposal for something slightly larger and ask for comments?

2024-05-14 16:40 UTC, benfdking commented
> I would change it to Feature Request. RFC is confusing

@louisjoecodes We already have a Feature Request, I do think it might be nice to have a more RFC like document where you can write a proposal for something slightly larger and ask for comments?

2024-05-15 10:06 UTC, louisjoecodes approved these changes

2024-05-15 11:06 UTC, merged